#init
backbone: densenet
weights: best_densenet2_gtsrb2tt100k_final.h5
test: gtsrb
dim: 64

#training parameter
batch: 128
epoch: 3
lr: 2.0e-4

#save params
outfile: dense_ft
loss: mse


